Generate cron from config files

diff --git a/bin/bacliup b/bin/bacliup
--- a/bin/bacliup
+++ b/bin/bacliup
@@ -9,6 +9,17 @@ function create_temporary_directory() {
   fi
 }
 
+function check_gpg_recipient_available() {
+  local recipient="$1"
+  test -n "$("$gpg_bin" --armor --batch --export "$1" 2>/dev/null)"
+}
+
+function check_rclone_remote_available() {
+  local remote="$1"
+  local available_remotes=("$(rclone --config "$rclone_config_file" listremotes)")
+  element_in_array "${remote}:" "${available_remotes[@]}"
+}
+
 function element_in_array() {
   local element="$1"
   shift
@@ -22,15 +33,22 @@ function element_in_array() {
   return 1
 }
 
-function check_gpg_recipient_available() {
-  local recipient="$1"
-  test -n "$("$gpg_bin" --armor --batch --export "$1" 2>/dev/null)"
+function fail() {
+  >&2 echo "$@"
+  exit 1
 }
 
-function check_rclone_remote_available() {
-  local remote="$1"
-  local available_remotes=("$(rclone --config "$rclone_config_file" listremotes)")
-  element_in_array "${remote}:" "${available_remotes[@]}"
+function get_config_value() {
+  local type="$1"
+  local key="$2"
+
+  local path="${backup_configs_dir}/${type}"
+  test -f "$path" || return 0
+
+  cat "$path" | \
+    grep "^${key} " | \
+    tail -n 1 | \
+    sed "s/^${key} //"
 }
 
 function get_rclone_remote_from_path() {
@@ -43,14 +61,98 @@ function is_macos() {
   [[ "$operating_system_name" == "darwin" ]]
 }
 
-fail() {
-  >&2 echo "$@"
-  exit 1
+function list_configs() {
+  if test -d "$backup_configs_dir"; then
+    ls -1 "$backup_configs_dir"
+  fi
 }
 
-local_cleanup() {
+function local_cleanup() {
   local tmp_dir="$1"
   test -d "$tmp_dir" && rm -fr "$tmp_dir"
+}
+
+
+
+# Features
+# ========
+
+function back_up() {
+  local backup_timestamp="$(date -u "+%Y%m%dT%H%M%SZ")"
+  local backup_directory_name="${backup_name}.${backup_timestamp}"
+  local current_backup_dir="${tmp_dir}/${backup_directory_name}"
+  local current_backup_basename="${backup_directory_name}.tar.gpg"
+
+  mkdir "$current_backup_dir"
+
+  BACKUP_DIR="$current_backup_dir" "$backup_script"
+
+  local tar_cmd=("$tar_bin" -C "$(dirname "$current_backup_dir")" -cf - "$(basename "$current_backup_dir")")
+
+  local gpg_cmd=("$gpg_bin" "--armor" "--batch" "--encrypt")
+  for recipient in "${gpg_recipients[@]}"; do
+    check_gpg_recipient_available "$recipient" || \
+      fail "GPG recipient '${recipient}' cannot be found. Is the GPG key in the keyring?"
+
+    gpg_cmd+=("--recipient" "$recipient")
+  done
+
+  local rclone_remote="$(get_rclone_remote_from_path "$backup_to")"
+  test -n "$rclone_remote" || fail "Backup destination ${backup_to} must be an rclone path specifying a remote, e.g. 'dest:path'"
+  check_rclone_remote_available "$rclone_remote" || fail "Backup remote $rclone_remote cannot be found. Is it defined in the rclone configuration file?"
+  local rclone_dest="${backup_to%/}/${current_backup_basename}"
+  local rclone_cmd=("$rclone_bin" rcat --config "$rclone_config_file" "$rclone_dest")
+
+  local raw_size_file="${tmp_dir}/raw-size.pv"
+  local final_size_file="${tmp_dir}/final-size.pv"
+  local now="$(date "+%s")"
+
+  "${tar_cmd[@]}" | \
+    "${gpg_cmd[@]}" | \
+    pv -bf 2>"$final_size_file" | \
+    "${rclone_cmd[@]}"
+
+  local backup_size="$(cat "$final_size_file" | tr -cd '[:alnum:]._-')"
+  local now_after="$(date "+%s")"
+  local elapsed_seconds="$(($now_after-$now))"
+
+  if test -n "$slack_webhook"; then
+    local backup_message="Successful"
+    test -n "$backup_type" && backup_message="$backup_message $backup_type"
+    backup_message="$backup_message backup for $backup_name"
+
+    local backup_duration="${elapsed_seconds}s"
+    test "$elapsed_seconds" -eq 0 && backup_duration="< 1s"
+
+    cat "${templates_dir}/slack-success.json" | \
+      backup_message="$backup_message" backup_name="$backup_name" backup_type="$backup_type" backup_duration="$backup_duration" backup_size="\`${backup_size}\`" backup_destination="\`${rclone_dest}\`" envsubst | \
+      "$curl_bin" \
+        --data-binary @- \
+        -H "Content-Type: application/json" \
+        "$slack_webhook"
+  fi
+}
+
+function generate_backup_cron() {
+  local cron="$(cat <<EOF
+# ┌───────────── minute (0 - 59)
+# │ ┌───────────── hour (0 - 23)
+# │ │ ┌───────────── day of the month (1 - 31)
+# │ │ │ ┌───────────── month (1 - 12)
+# │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
+# │ │ │ │ │                                   7 is also Sunday on some systems)
+# │ │ │ │ │
+# │ │ │ │ │
+# * * * * * <command to execute>
+EOF
+)"
+
+  for backup_config in "$(list_configs)"; do
+    cron_schedule="$(get_config_value "$backup_config" cron)"
+    cron="$(printf "${cron}\n\n${cron_schedule} /usr/local/bin/bacliup $backup_config &>/dev/stdout\n")"
+  done
+
+  echo "$cron"
 }
 
 
@@ -68,10 +170,11 @@ rclone_bin="${BACLIUP_RCLONE_BIN:-rclone}"
 tar_bin="${BACLIUP_TAR_BIN:-tar}"
 
 # Backup options
-backup_name="${BACLIUP_BACKUP_NAME:-default}"
-backup_interval="$BACLIUP_BACKUP_INTERVAL"
+backup_type="${BACLIUP_BACKUP_TYPE:-default}"
+backup_name="${BACLIUP_BACKUP_NAME:-backup}"
+backup_configs_dir="${BACLIUP_BACKUP_CONFIGS_DIR:-/etc/bacliup/backups}"
 backup_script="${BACLIUP_BACKUP_SCRIPT:-/usr/local/bin/backup}"
-backup_to="${BACLIUP_BACKUP_TO:-dest:}"
+backup_to="${BACLIUP_BACKUP_TO:-"dest:"}"
 IFS=',' read -r -a gpg_recipients <<< "$BACLIUP_GPG_RECIPIENT"
 gpg_cli_recipients=()
 templates_dir="${BACLIUP_TEMPLATES_DIR:-"${script_path}/../templates"}"
@@ -124,12 +227,19 @@ set -- "${positional_args[@]}"
 # Override environment variables with command-line arguments.
 test "${#gpg_cli_recipients[@]}" -ge 1 && gpg_recipients=("${gpg_cli_recipients[@]}")
 
-test "$#" -gt 0 && fail "Positional arguments not supported: ${positional_args[@]}"
+action="backup"
+if [[ "$1" == "cron" ]]; then
+  action="cron"
+  shift
+elif test "$#" -gt 1; then
+  backup_type="$1"
+  shift
+fi
 
+test "$#" -gt 0 && fail "Only one position argument is supported. Extra arguments: $@"
 
-
-# Backup
-# ======
+backup_to="$(get_config_value "to")"
+backup_to="${backup_to:-${BACLIUP_BACKUP_TO:-dest:}}"
 
 tmp_dir=`create_temporary_directory`
 trap "local_cleanup $tmp_dir" EXIT
@@ -137,60 +247,8 @@ trap "local_cleanup $tmp_dir" EXIT
 log_file="${tmp_dir}/bacliup.log"
 exec &> >(tee -a "$log_file")
 
-function back_up() {
-  local backup_timestamp="$(date -u "+%Y%m%dT%H%M%SZ")"
-  local backup_directory_name="backup.${backup_timestamp}"
-  local current_backup_dir="${tmp_dir}/${backup_directory_name}"
-  local current_backup_basename="${backup_directory_name}.tar.gpg"
-
-  mkdir "$current_backup_dir"
-
-  BACKUP_DIR="$current_backup_dir" "$backup_script"
-
-  local tar_cmd=("$tar_bin" -C "$(dirname "$current_backup_dir")" -cf - "$(basename "$current_backup_dir")")
-
-  local gpg_cmd=("$gpg_bin" "--armor" "--batch" "--encrypt")
-  for recipient in "${gpg_recipients[@]}"; do
-    check_gpg_recipient_available "$recipient" || \
-      fail "GPG recipient '${recipient}' cannot be found. Is the GPG key in the keyring?"
-
-    gpg_cmd+=("--recipient" "$recipient")
-  done
-
-  local rclone_remote="$(get_rclone_remote_from_path "$backup_to")"
-  test -n "$rclone_remote" || fail "Backup destination ${backup_to} must be an rclone path specifying a remote, e.g. 'dest:path'"
-  check_rclone_remote_available "$rclone_remote" || fail "Backup remote $rclone_remote cannot be found. Is it defined in the rclone configuration file?"
-  local rclone_dest="${backup_to%/}/${current_backup_basename}"
-  local rclone_cmd=("$rclone_bin" rcat --config "$rclone_config_file" "$rclone_dest")
-
-  local raw_size_file="${tmp_dir}/raw-size.pv"
-  local final_size_file="${tmp_dir}/final-size.pv"
-  local now="$(date "+%s")"
-
-  "${tar_cmd[@]}" | \
-    "${gpg_cmd[@]}" | \
-    pv -bf 2>"$final_size_file" | \
-    "${rclone_cmd[@]}"
-
-  local backup_size="$(cat "$final_size_file" | tr -cd '[:alnum:]._-')"
-  local now_after="$(date "+%s")"
-  local elapsed_seconds="$(($now_after-$now))"
-
-  if test -n "$slack_webhook"; then
-    local backup_message="Successful"
-    test -n "$backup_interval" && backup_message="$backup_message $backup_interval"
-    backup_message="$backup_message backup for $backup_name"
-
-    local backup_duration="${elapsed_seconds}s"
-    test "$elapsed_seconds" -eq 0 && backup_duration="< 1s"
-
-    cat "${templates_dir}/slack-success.json" | \
-      backup_message="$backup_message" backup_name="$backup_name" backup_interval="${backup_interval:-"_None_"}" backup_duration="$backup_duration" backup_size="\`${backup_size}\`" backup_destination="\`${rclone_dest}\`" envsubst | \
-      "$curl_bin" \
-        --data-binary @- \
-        -H "Content-Type: application/json" \
-        "$slack_webhook"
-  fi
-}
-
-back_up
+if [[ "$action" == "backup" ]]; then
+  back_up
+elif [[ "$action" == "cron" ]]; then
+  generate_backup_cron
+fi
